package com.guhanjie.model;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.amount
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.tip
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    private BigDecimal tip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.from
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    private Integer from;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.waypoints
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    private String waypoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.to
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    private Integer to;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.distance
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    private BigDecimal distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.vehicle
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    private Byte vehicle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.remark
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.update_time
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.amount
     *
     * @return the value of order.amount
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.amount
     *
     * @param amount the value for order.amount
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.tip
     *
     * @return the value of order.tip
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public BigDecimal getTip() {
        return tip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.tip
     *
     * @param tip the value for order.tip
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public void setTip(BigDecimal tip) {
        this.tip = tip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.from
     *
     * @return the value of order.from
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public Integer getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.from
     *
     * @param from the value for order.from
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public void setFrom(Integer from) {
        this.from = from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.waypoints
     *
     * @return the value of order.waypoints
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public String getWaypoints() {
        return waypoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.waypoints
     *
     * @param waypoints the value for order.waypoints
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public void setWaypoints(String waypoints) {
        this.waypoints = waypoints == null ? null : waypoints.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.to
     *
     * @return the value of order.to
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public Integer getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.to
     *
     * @param to the value for order.to
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public void setTo(Integer to) {
        this.to = to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.distance
     *
     * @return the value of order.distance
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public BigDecimal getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.distance
     *
     * @param distance the value for order.distance
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public void setDistance(BigDecimal distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.vehicle
     *
     * @return the value of order.vehicle
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public Byte getVehicle() {
        return vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.vehicle
     *
     * @param vehicle the value for order.vehicle
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public void setVehicle(Byte vehicle) {
        this.vehicle = vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.remark
     *
     * @return the value of order.remark
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.remark
     *
     * @param remark the value for order.remark
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.update_time
     *
     * @return the value of order.update_time
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.update_time
     *
     * @param updateTime the value for order.update_time
     *
     * @mbggenerated Wed Aug 31 23:55:02 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}