package com.guhanjie.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.amount
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.tip
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private BigDecimal tip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.from_id
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private Integer fromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.waypoints_ids
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private String waypointsIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.to_id
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private Integer toId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.distance
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private BigDecimal distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.vehicle
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private Short vehicle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.workers
     *
     * @mbggenerated Sat Oct 01 20:49:39 CST 2016
     */
    private Integer workers;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.contactor
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private String contactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.phone
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.remark
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_type
     *
     * @mbggenerated Sat Oct 01 20:49:39 CST 2016
     */
    private Short payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_status
     *
     * @mbggenerated Sat Oct 01 20:49:39 CST 2016
     */
    private Short payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_time
     *
     * @mbggenerated Sat Oct 01 20:49:39 CST 2016
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.start_time
     *
     * @mbggenerated Sat Sep 10 14:15:30 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.update_time
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private Date updateTime;
    
    //------------------------- custom add -----------------------------
    private User user;
    private Position from;
    private Position to;
    private List<Position> waypoints;
    
    public User getUser() {
        return user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    
    public Position getFrom() {
        return from;
    }
    
    public void setFrom(Position from) {
        this.from = from;
    }
    
    public Position getTo() {
        return to;
    }
    
    public void setTo(Position to) {
        this.to = to;
    }
    
    public List<Position> getWaypoints() {
        return waypoints;
    }
    
    public void setWaypoints(List<Position> waypoints) {
        this.waypoints = waypoints;
    }
    //--------------------------------------------------------------------

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.amount
     *
     * @return the value of order.amount
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.amount
     *
     * @param amount the value for order.amount
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.tip
     *
     * @return the value of order.tip
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public BigDecimal getTip() {
        return tip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.tip
     *
     * @param tip the value for order.tip
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setTip(BigDecimal tip) {
        this.tip = tip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.from_id
     *
     * @return the value of order.from_id
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.from_id
     *
     * @param fromId the value for order.from_id
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.waypoints_ids
     *
     * @return the value of order.waypoints_ids
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public String getWaypointsIds() {
        return waypointsIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.waypoints_ids
     *
     * @param waypointsIds the value for order.waypoints_ids
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setWaypointsIds(String waypointsIds) {
        this.waypointsIds = waypointsIds == null ? null : waypointsIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.to_id
     *
     * @return the value of order.to_id
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.to_id
     *
     * @param toId the value for order.to_id
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.distance
     *
     * @return the value of order.distance
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public BigDecimal getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.distance
     *
     * @param distance the value for order.distance
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setDistance(BigDecimal distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.vehicle
     *
     * @return the value of order.vehicle
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public Short getVehicle() {
        return vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.vehicle
     *
     * @param vehicle the value for order.vehicle
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setVehicle(Short vehicle) {
        this.vehicle = vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.workers
     *
     * @return the value of order.workers
     *
     * @mbggenerated Sat Oct 01 20:49:39 CST 2016
     */
    public Integer getWorkers() {
        return workers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.workers
     *
     * @param workers the value for order.workers
     *
     * @mbggenerated Sat Oct 01 20:49:39 CST 2016
     */
    public void setWorkers(Integer workers) {
        this.workers = workers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.contactor
     *
     * @return the value of order.contactor
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public String getContactor() {
        return contactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.contactor
     *
     * @param contactor the value for order.contactor
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setContactor(String contactor) {
        this.contactor = contactor == null ? null : contactor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.phone
     *
     * @return the value of order.phone
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.phone
     *
     * @param phone the value for order.phone
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.remark
     *
     * @return the value of order.remark
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.remark
     *
     * @param remark the value for order.remark
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_type
     *
     * @return the value of order.pay_type
     *
     * @mbggenerated Sat Oct 01 20:49:39 CST 2016
     */
    public Short getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_type
     *
     * @param payType the value for order.pay_type
     *
     * @mbggenerated Sat Oct 01 20:49:39 CST 2016
     */
    public void setPayType(Short payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_status
     *
     * @return the value of order.pay_status
     *
     * @mbggenerated Sat Oct 01 20:49:39 CST 2016
     */
    public Short getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_status
     *
     * @param payStatus the value for order.pay_status
     *
     * @mbggenerated Sat Oct 01 20:49:39 CST 2016
     */
    public void setPayStatus(Short payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_time
     *
     * @return the value of order.pay_time
     *
     * @mbggenerated Sat Oct 01 20:49:39 CST 2016
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_time
     *
     * @param payTime the value for order.pay_time
     *
     * @mbggenerated Sat Oct 01 20:49:39 CST 2016
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.start_time
     *
     * @return the value of order.start_time
     *
     * @mbggenerated Sat Sep 10 14:15:30 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.start_time
     *
     * @param startTime the value for order.start_time
     *
     * @mbggenerated Sat Sep 10 14:15:30 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.update_time
     *
     * @return the value of order.update_time
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.update_time
     *
     * @param updateTime the value for order.update_time
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
}