package com.guhanjie.model;

public class Position {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.id
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.address
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.detail
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.floor
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private Short floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.geo_lat
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private String geoLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.geo_lng
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    private String geoLng;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.id
     *
     * @return the value of position.id
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.id
     *
     * @param id the value for position.id
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.address
     *
     * @return the value of position.address
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.address
     *
     * @param address the value for position.address
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.detail
     *
     * @return the value of position.detail
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.detail
     *
     * @param detail the value for position.detail
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.floor
     *
     * @return the value of position.floor
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public Short getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.floor
     *
     * @param floor the value for position.floor
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setFloor(Short floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.geo_lat
     *
     * @return the value of position.geo_lat
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public String getGeoLat() {
        return geoLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.geo_lat
     *
     * @param geoLat the value for position.geo_lat
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setGeoLat(String geoLat) {
        this.geoLat = geoLat == null ? null : geoLat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.geo_lng
     *
     * @return the value of position.geo_lng
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public String getGeoLng() {
        return geoLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.geo_lng
     *
     * @param geoLng the value for position.geo_lng
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    public void setGeoLng(String geoLng) {
        this.geoLng = geoLng == null ? null : geoLng.trim();
    }
}