package com.guhanjie.mapper;

import java.util.List;

import com.guhanjie.model.Order;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Thu Sep 01 14:34:30 CST 2016
     */
    int updateByPrimaryKey(Order record);
    
    //------------------------- custom add -----------------------------
    List<Order> selectByUserId(Integer userid);
    //--------------------------------------------------------------------
}